### PR TITLE
Added transformations (scale, rotate, translate)

### PR DESCRIPTION
**Pull request by joostn**
Hi Evan,

Thanks for creating csg.js! I've added affine transformations for translation, rotation, scaling and arbitrary matrix transform. See tests/index.html where I've added an example.

I'm planning to add STL output as well, this would make it a great alternative to OpenSCAD for generating models for 3D printing.

Joost

### CODE REVIEW

**Comment by joostn** [comment]
And STL output is now implemented as well. I've included a quick demo at tests/stl.html.

**Comment by joostn** [comment]
I've added support for 2D shapes, and extrusion into a 3D mesh. See tests/index.html for a demo

**Comment by evanw** [comment]
I meant for csg.js to be a simple, readable implementation of the algorithm and not to be a production-quality CAD library for 3D geometry generation. Matrix transformations and STL output do not aid in understanding the algorithm and so I would rather keep them out of csg.js. You're welcome to use csg.js as the starting point for such a library, just keep in mind the limitations I mentioned on your other pull request.

**Comment by joostn** [comment]
That's fine, I'll keep working on my port then.

**Pull request closed without merging**
